CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."EMPLEADOS_ID_AUTOINCREMENT" 
BEFORE INSERT ON EMPLEADOS
FOR EACH ROW
BEGIN
  SELECT SEQ_EMPLEADOS_ID.NEXTVAL
  INTO :NEW.ID
  FROM dual;
END;

/
ALTER TRIGGER "ADMIN"."EMPLEADOS_ID_AUTOINCREMENT" ENABLE;

