CREATE TABLE "ADMIN"."TCG" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"PRECIO" NUMBER(10,2), 
	"STOCK" NUMBER(10,0), 
	"VENTAS" NUMBER(10,0) DEFAULT 0, 
	"TIPO" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"JUEGO" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "ADMIN"."PK_TCG" ON "ADMIN"."TCG" ("ID") 
  ;

ALTER TABLE "ADMIN"."TCG" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."TCG" MODIFY ("NOMBRE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."TCG" MODIFY ("STOCK" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."TCG" MODIFY ("TIPO" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."TCG" ADD CONSTRAINT "PK_TCG" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

