CREATE TABLE "ADMIN"."JUEGOS_MESA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PRECIO" BINARY_DOUBLE, 
	"STOCK" NUMBER, 
	"GENERO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NUMERO_JUGADORES" NUMBER, 
	"VENTAS" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

ALTER TABLE "ADMIN"."JUEGOS_MESA" MODIFY ("NOMBRE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."JUEGOS_MESA" MODIFY ("STOCK" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."JUEGOS_MESA" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_JUEGOS_MESA_ID" 
BEFORE INSERT ON Juegos_mesa
FOR EACH ROW
BEGIN
  IF :NEW.id IS NULL THEN
    :NEW.id := seq_juegos_mesa_id.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "ADMIN"."TRG_JUEGOS_MESA_ID" ENABLE;

