CREATE TABLE "ADMIN"."EMPLEADOS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"APELLIDOS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CORREO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"TIPOEMPLEADO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CONTRASEÑA" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

ALTER TABLE "ADMIN"."EMPLEADOS" MODIFY ("NOMBRE" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."EMPLEADOS" MODIFY ("APELLIDOS" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."EMPLEADOS" MODIFY ("CORREO" NOT NULL ENABLE);

ALTER TABLE "ADMIN"."EMPLEADOS" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."EMPLEADOS_ID_AUTOINCREMENT" 
BEFORE INSERT ON EMPLEADOS
FOR EACH ROW
BEGIN
  SELECT SEQ_EMPLEADOS_ID.NEXTVAL
  INTO :NEW.ID
  FROM dual;
END;

/
ALTER TRIGGER "ADMIN"."EMPLEADOS_ID_AUTOINCREMENT" ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_EMPLEADOS_CORREO" 

BEFORE INSERT ON EMPLEADOS

FOR EACH ROW

BEGIN

  IF :new.APELLIDOS IS NOT NULL AND :new.NOMBRE IS NOT NULL THEN

    :new.CORREO := LOWER(SUBSTR(:new.APELLIDOS, 1, 3) || :new.ID || SUBSTR(:new.NOMBRE, 1, INSTR(:new.NOMBRE, ' ') - 1) || '@magicas.es');

  END IF;

END;
/
ALTER TRIGGER "ADMIN"."TRG_EMPLEADOS_CORREO" ENABLE;

