CREATE TABLE TCG (
    id NUMBER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    juego VARCHAR2(20) NOT NULL,
    tipo VARCHAR2(20) NOT NULL,
    precio BINARY_DOUBLE,
    stock NUMBER NOT NULL,
    ventas NUMBER DEFAULT 0,
    CONSTRAINT pk_tcg PRIMARY KEY (id)
);