CREATE SEQUENCE SEQ_SOCIOS_ID
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
CACHE 20;



CREATE TABLE SOCIOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    TELEFONO NUMBER NOT NULL,
    CORREO VARCHAR2(50)
);


CREATE OR REPLACE TRIGGER trg_socios_id
BEFORE INSERT ON SOCIOS
FOR EACH ROW
BEGIN
    SELECT SEQ_SOCIOS_ID.NEXTVAL INTO :new.ID FROM dual;
END;