CREATE SEQUENCE SEQ_JUEGOS_ID
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
CACHE 20;

CREATE OR REPLACE TRIGGER trg_juego_id
BEFORE INSERT ON JUEGOS_MESA
FOR EACH ROW
BEGIN
    SELECT SEQ_JUEGOS_ID.NEXTVAL INTO :new.ID FROM dual;
END;

/

CREATE TABLE JUEGOS_MESA (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    PRECIO NUMBER,
    STOCK NUMBER NOT NULL
);
