CREATE SEQUENCE seq_empleados_id
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
CACHE 20;

CREATE TABLE EMPLEADOS (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(50) NOT NULL
);
